# Makefile for testStringBinaryTrace0 (Allwinner T527 XuanTie E907)

ARCH_FLAGS = -march=rv32imafc_zicsr_zifencei_zihintpause -mabi=ilp32 -mcmodel=medany

APP_SRCS_CPP = main.cpp

include ../../common/common.mk

