################################################################################
#
# aic8800-driver
#
################################################################################

AIC8800_DRIVER_SITE = /home/tcmichals/projects/cubie/cubie-a5e/aic8800-driver-src
AIC8800_DRIVER_SITE_METHOD = local
AIC8800_DRIVER_LICENSE = GPL-2.0

AIC8800_DRIVER_MODULE_SUBDIRS = drivers/aic8800

AIC8800_DRIVER_MODULE_MAKE_OPTS = \
	KDIR=$(LINUX_DIR) \
	KSRC=$(LINUX_DIR) \
	ARCH=arm64 \
	CROSS_COMPILE=$(TARGET_CROSS) \
	CONFIG_AIC8800_WLAN_SUPPORT=m

ifeq ($(BR2_PACKAGE_AIC8800_DRIVER_SDIO),y)
AIC8800_DRIVER_MODULE_MAKE_OPTS += CONFIG_SDIO_SUPPORT=y
else
AIC8800_DRIVER_MODULE_MAKE_OPTS += CONFIG_SDIO_SUPPORT=n
endif

ifeq ($(BR2_PACKAGE_AIC8800_DRIVER_USB),y)
AIC8800_DRIVER_MODULE_MAKE_OPTS += CONFIG_USB_SUPPORT=y
AIC8800_DRIVER_MODULE_MAKE_OPTS += CONFIG_AIC_LOADFW_SUPPORT=m
else
AIC8800_DRIVER_MODULE_MAKE_OPTS += CONFIG_USB_SUPPORT=n
AIC8800_DRIVER_MODULE_MAKE_OPTS += CONFIG_AIC_LOADFW_SUPPORT=n
endif

$(eval $(kernel-module))
$(eval $(generic-package))

