#!/bin/sh
#
# S60riscv: Startup initialization for XuanTie E907 RISC-V co-processor
#

case "$1" in
    start)
        /usr/bin/load-riscv.sh start
        ;;
    stop)
        /usr/bin/load-riscv.sh stop
        ;;
    restart|reload)
        /usr/bin/load-riscv.sh restart
        ;;
    status)
        /usr/bin/load-riscv.sh status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
