# Makefile for testPingRpmsgSram (Allwinner T527 XuanTie E907)
# Pure On-Chip SRAM Space 1 VirtIO vrings

DEFINES += -DCONFIG_RPROC_RPMSG -DCONFIG_VRING0_DA=0x40040000 -DCONFIG_VRING1_DA=0x40042000
APP_SRCS_CPP = main.cpp

include ../../common/common.mk
